spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5435/${POSTGRES_DB}
    #url: jdbc:postgresql://postgres:5432/${POSTGRES_DB} lors de la connexion à la base de données depuis le conteneur de l'application
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
      host: localhost
      port: 1025
      username: ""
      password: ""
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: false
    
server:
  port: ${SERVER_PORT}
app:
  url: http://localhost:${SERVER_PORT}
  frontend-url: ${APP_FRONTEND_URL:http://localhost:${APP_FRONTEND_PORT}}
  name: EcommerceApp
  tax:
    rate: 0.20
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

