spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5435/${POSTGRES_DB}
    #url: jdbc:postgresql://postgres:5432/${POSTGRES_DB} lors de la connexion à la base de données depuis le conteneur de l'application
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a513d95063c91d
    password: dbdb9605c78f76
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}

app:
  url: "http://localhost:${SERVER_PORT}"